# Site settings
title: SAUCY.LIFE
email: your-email@example.com
description: >-
  Personal photography portfolio
baseurl: "" # the subpath of your site
url: "https://saucy.life" # your custom domain

# Jekyll environment settings (used for conditional logic)
# This helps us handle different environments (local vs GitHub Pages)
github_pages: true

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - scripts/
  - README.md

# Collections
collections:
  albums:
    output: true
    permalink: /album/:path/
  stuff:
    output: true
    permalink: /stuff/:path/

defaults:
  - scope:
      path: ""
      type: "albums"
    values:
      layout: "album"
  - scope:
      path: ""
      type: "stuff"
    values:
      layout: "stuff-item"
  - scope:
      path: ""
    values:
      layout: "default"