# Site settings
title: SAUCY.LIFE
email: your-email@example.com
description: >-
  Personal photography portfolio
baseurl: "/photo-gallery" # the subpath of your site for GitHub Pages
url: "https://rtmurase.github.io" # the base hostname & protocol for your site

# Jekyll environment settings (used for conditional logic)
# This helps us handle different environments (local vs GitHub Pages)
github_pages: true

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - scripts/
  - README.md

# Collections
collections:
  albums:
    output: true
    permalink: /album/:path/

defaults:
  - scope:
      path: ""
      type: "albums"
    values:
      layout: "album"
  - scope:
      path: ""
    values:
      layout: "default"