# Site settings
title: SAUCY.LIFE
email: your-email@example.com
description: >-
  Personal photography portfolio
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - scripts/
  - README.md

# Collections
collections:
  albums:
    output: true
    permalink: /album/:path/

defaults:
  - scope:
      path: ""
      type: "albums"
    values:
      layout: "album"
  - scope:
      path: ""
    values:
      layout: "default"